package reporter_test

import (
	"bytes"
	"context"
	"strings"
	"testing"

	"github.com/nixbpe/ari/internal/checker"
	"github.com/nixbpe/ari/internal/reporter"
	"github.com/nixbpe/ari/internal/scorer"
)

func TestTextReporterOutput(t *testing.T) {
	r := reporter.BuildReport(makeRepoInfo(), makeScore(), makeResults())
	tr := &reporter.TextReporter{}

	var buf bytes.Buffer
	err := tr.Report(context.Background(), r, &buf)
	if err != nil {
		t.Fatalf("Report() error: %v", err)
	}

	output := buf.String()
	if output == "" {
		t.Fatal("Report() produced empty output")
	}

	// Check for ANSI escape codes
	if strings.Contains(output, "\x1b[") || strings.Contains(output, "\033[") {
		t.Error("Output contains ANSI escape codes")
	}

	// Check for required content
	if !strings.Contains(output, "/test/repo") {
		t.Error("Output missing repository path")
	}
	if !strings.Contains(output, "Functional") {
		t.Error("Output missing level")
	}
	if !strings.Contains(output, "75%") {
		t.Error("Output missing pass rate")
	}
}

func TestTextReporterPillars(t *testing.T) {
	r := reporter.BuildReport(makeRepoInfo(), makeScore(), makeResults())
	tr := &reporter.TextReporter{}

	var buf bytes.Buffer
	err := tr.Report(context.Background(), r, &buf)
	if err != nil {
		t.Fatalf("Report() error: %v", err)
	}

	output := buf.String()

	if !strings.Contains(output, "Environment & Infra") {
		t.Error("Output missing 'Environment & Infra' pillar")
	}
	if !strings.Contains(output, "Constraints & Governance") {
		t.Error("Output missing 'Constraints & Governance' pillar")
	}
}

func TestTextReporterSuggestions(t *testing.T) {
	r := reporter.BuildReport(makeRepoInfo(), makeScore(), makeResults())
	tr := &reporter.TextReporter{}

	var buf bytes.Buffer
	err := tr.Report(context.Background(), r, &buf)
	if err != nil {
		t.Fatalf("Report() error: %v", err)
	}

	output := buf.String()

	// Check for suggestions section
	if !strings.Contains(output, "Suggestions:") {
		t.Error("Output missing 'Suggestions:' section")
	}

	// Check for failing criterion in suggestions
	if !strings.Contains(output, "CI configuration present") {
		t.Error("Output missing failing criterion in suggestions")
	}
}

func TestTextReporterSkipped(t *testing.T) {
	r := reporter.BuildReport(makeRepoInfo(), makeScore(), makeResults())
	tr := &reporter.TextReporter{}

	var buf bytes.Buffer
	err := tr.Report(context.Background(), r, &buf)
	if err != nil {
		t.Fatalf("Report() error: %v", err)
	}

	output := buf.String()

	// Check for skipped symbol
	if !strings.Contains(output, "↷") {
		t.Error("Output missing skipped symbol (↷)")
	}

	// Check for passed symbol
	if !strings.Contains(output, "✓") {
		t.Error("Output missing passed symbol (✓)")
	}

	// Check for failed symbol
	if !strings.Contains(output, "✗") {
		t.Error("Output missing failed symbol (✗)")
	}
}

func TestTextReporterHeader(t *testing.T) {
	r := reporter.BuildReport(makeRepoInfo(), makeScore(), makeResults())
	tr := &reporter.TextReporter{}

	var buf bytes.Buffer
	err := tr.Report(context.Background(), r, &buf)
	if err != nil {
		t.Fatalf("Report() error: %v", err)
	}

	output := buf.String()

	// Check for header
	if !strings.Contains(output, "ari — Agent Readiness Index") {
		t.Error("Output missing header")
	}
	if !strings.Contains(output, "============================") {
		t.Error("Output missing header separator")
	}
	if !strings.Contains(output, "Repository:") {
		t.Error("Output missing 'Repository:' label")
	}
	if !strings.Contains(output, "Language:") {
		t.Error("Output missing 'Language:' label")
	}
	if !strings.Contains(output, "Level:") {
		t.Error("Output missing 'Level:' label")
	}
	if !strings.Contains(output, "Pass Rate:") {
		t.Error("Output missing 'Pass Rate:' label")
	}
}

func TestTextReporterFooter(t *testing.T) {
	r := reporter.BuildReport(makeRepoInfo(), makeScore(), makeResults())
	tr := &reporter.TextReporter{}

	var buf bytes.Buffer
	err := tr.Report(context.Background(), r, &buf)
	if err != nil {
		t.Fatalf("Report() error: %v", err)
	}

	output := buf.String()

	// Check for footer
	if !strings.Contains(output, "Generated by ari") {
		t.Error("Output missing footer")
	}
	if !strings.Contains(output, "0.1.0") {
		t.Error("Output missing version in footer")
	}
}

func TestTextReporterEmptyResults(t *testing.T) {
	repoInfo := makeRepoInfo()
	score := &scorer.Score{
		Level:    checker.LevelFunctional,
		PassRate: 0.0,
	}
	results := []*checker.Result{}

	r := reporter.BuildReport(repoInfo, score, results)
	tr := &reporter.TextReporter{}

	var buf bytes.Buffer
	err := tr.Report(context.Background(), r, &buf)
	if err != nil {
		t.Fatalf("Report() error: %v", err)
	}

	output := buf.String()
	if output == "" {
		t.Fatal("Report() produced empty output for empty results")
	}

	// Should still have header and footer
	if !strings.Contains(output, "ari — Agent Readiness Index") {
		t.Error("Output missing header for empty results")
	}
	if !strings.Contains(output, "Generated by ari") {
		t.Error("Output missing footer for empty results")
	}
}
