package reporter

import (
	"context"
	"fmt"
	"io"
)

type TextReporter struct{}

func (t *TextReporter) Report(ctx context.Context, report *Report, w io.Writer) error {
	// Header
	fmt.Fprintf(w, "ari — Agent Readiness Index\n")
	fmt.Fprintf(w, "============================\n")
	fmt.Fprintf(w, "Repository: %s\n", report.RepoPath)
	fmt.Fprintf(w, "Language:   %s\n", report.Language)
	fmt.Fprintf(w, "Level:      %s\n", report.Level)
	fmt.Fprintf(w, "Pass Rate:  %.0f%% (%d/%d)\n\n", report.PassRate*100, int(report.PassRate*float64(len(report.CriteriaResults))), len(report.CriteriaResults))

	// Group criteria by pillar
	pillarMap := make(map[string][]CriterionReport)
	pillarOrder := []string{}
	pillarSeen := make(map[string]bool)

	for _, cr := range report.CriteriaResults {
		if !pillarSeen[cr.Pillar] {
			pillarOrder = append(pillarOrder, cr.Pillar)
			pillarSeen[cr.Pillar] = true
		}
		pillarMap[cr.Pillar] = append(pillarMap[cr.Pillar], cr)
	}

	// Output criteria grouped by pillar
	for _, pillar := range pillarOrder {
		criteria := pillarMap[pillar]
		passed := 0
		total := 0

		for _, cr := range criteria {
			if !cr.Skipped {
				total++
				if cr.Passed {
					passed++
				}
			}
		}

		percentage := 0
		if total > 0 {
			percentage = (passed * 100) / total
		}

		fmt.Fprintf(w, "%s: %d/%d (%d%%)\n", pillar, passed, total, percentage)

		for _, cr := range criteria {
			symbol := "✓"
			if cr.Skipped {
				symbol = "↷"
			} else if !cr.Passed {
				symbol = "✗"
			}

			fmt.Fprintf(w, "  %s %s — %s\n", symbol, cr.ID, cr.Name)
		}

		fmt.Fprintf(w, "\n")
	}

	// Suggestions section
	if len(report.Suggestions) > 0 {
		fmt.Fprintf(w, "Suggestions:\n")
		for i, sugg := range report.Suggestions {
			fmt.Fprintf(w, "  %d. [%s] %s: %s\n", i+1, sugg.Priority, sugg.Title, sugg.Description)
		}
		fmt.Fprintf(w, "\n")
	}

	// Footer
	fmt.Fprintf(w, "Generated by ari v%s at %s\n", report.AriVersion, report.GeneratedAt.Format("2006-01-02 15:04:05"))

	return nil
}
